# Índices de Criminalidad de las Naciones Unidas

In [6]:
archivo = 'data/data_cts_intentional_homicide.xlsx'

In [16]:
!pip install numpy
!pip install pandas
!pip install openpyxl

Requirement already satisfied: numpy in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.24.2)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\lamat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas) (1.24.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\lamat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (3.1.1)
Requirement already satisfied: et-xmlfile in c:\users\lamat\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\lamat\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Librerías

- pandas: Manipulación de dataframes.

In [17]:
import pandas as pd
import numpy as np
from openpyxl import Workbook

## Lectura y preprocesamiento de datos

In [15]:
data = pd.read_excel(archivo, sheet_name='data_cts_intentional_homicide', header=2)
data.head()

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
0,ABW,Aruba,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,1990,Counts,0.0,MD
1,ABW,Aruba,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,1995,Counts,6.0,MD
2,ABW,Aruba,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,1999,Counts,2.0,MD
3,ABW,Aruba,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,2001,Counts,4.0,MD
4,ABW,Aruba,Americas,Latin America and the Caribbean,Victims of intentional homicide,Total,Total,Total,Total,2002,Counts,5.0,MD

Sólo nos interesa mantener la información de Latinoamérica. Quitamos los agregados de los totales para quedarnos únicamente con las categorías y no contar dos veces la información.

In [47]:
df = data.query("Subregion == 'Latin America and the Caribbean' and Dimension != 'Total' and Sex != 'Total'")
df

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
15476,ARG,Argentina,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member,Female,Total,2015,Counts,169.000000,CTS
15477,ARG,Argentina,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member: Intimate pa...,Female,Total,2015,Counts,120.000000,CTS
15478,ARG,Argentina,Americas,Latin America and the Caribbean,Victims of intentional homicide,by situational context,Other criminal activities,Female,Total,2015,Counts,32.000000,CTS
15487,ARG,Argentina,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member,Female,Total,2017,Counts,220.000000,CTS
15488,ARG,Argentina,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member: Intimate pa...,Female,Total,2017,Counts,150.000000,CTS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75083,VCT,Saint Vincent and the Grenadines,Americas,Latin America and the Caribbean,Victims of intentional homicide,by situational context,Organized criminal groups or gangs,Male,Total,2005,"Rate per 100,000 population",3.644846,CTS
75085,VCT,Saint Vincent and the Grenadines,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member,Male,Total,2006,"Rate per 100,000 population",1.820234,CTS
75087,VCT,Saint Vincent and the Grenadines,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member,Male,Total,2007,"Rate per 100,000 population",1.818843,CTS
75089,VCT,Saint Vincent and the Grenadines,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member,Male,Total,2008,"Rate per 100,000 population",5.453157,CTS
75092,VCT,Saint Vincent and the Grenadines,Americas,Latin America and the Caribbean,Victims of intentional homicide,by relationship to perpetrator,Intimate partner or family member,Male,Total,2012,"Rate per 100,000 population",5.428980,CTS

In [50]:
df['Category'].unique()

array(['Intimate partner or family member',
       'Intimate partner or family member: Intimate partner',
       'Other criminal activities',
       'Intimate partner or family member: Family member',
       'Other Perpetrator known to the victim', 'Perpetrator unknown',
       'Relationship to perpetrator is not known', 'National citizens',
       'Foreign citizens', 'Organized criminal groups or gangs',
       'Interpersonal homicide', 'Unknown types of homicide',
       'Socio-political homicide',
       'Socio-political homicide - terrorist offences'], dtype=object)

In [51]:
pd.pivot_table(df, values='VALUE', 
                   index=['Country'], 
                   columns=['Year'], 
                   aggfunc=np.sum)
                   #fill_value=0)

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country,,,,,,,,,,,,,,,,
Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.943391,39.459998,86.385006,58.575873,20.806557,42.155514
Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,987.607402,NaN,3180.627344,3284.964447,3168.287292,3231.453154
Bahamas,52.105862,63.128190,91.610916,76.626821,79.367023,113.372800,142.978204,170.540734,NaN,114.801729,251.968651,232.930194,385.972328,385.591409,302.139929,229.360500
Barbados,NaN,NaN,10.254645,5.059718,10.275868,20.291800,6.831446,8.447938,20.134215,20.541221,49.932551,62.801221,90.225760,112.057949,166.745684,227.689445
Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.490562,545.086872,635.919605,491.668773,507.146768,408.804889,465.543645
Bolivia (Plurinational State of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1330.855918,1708.056106,1972.429616,1538.785610,675.509122,NaN
Chile,17.209565,21.257456,36.433762,26.310923,14.166230,16.188699,22.256110,23.264610,142.592867,105.161961,145.598957,1589.782833,1980.576212,2041.816430,847.937501,1027.743288
Colombia,2846.502042,1532.174495,1684.784863,1519.940519,1698.688660,1724.729754,1162.155181,1217.347480,17764.114332,19014.396913,18412.663114,14531.594965,12534.843194,25613.355200,12233.141137,11603.126076
Costa Rica,NaN,71.122029,81.534475,121.188637,136.784576,120.016693,103.267938,68.812172,92.749640,594.797058,579.966380,NaN,NaN,NaN,NaN,NaN
Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,22.000000,33.000000,55.000000,40.000000,45.000000,40.000000
Dominican Republic,NaN,NaN,NaN,NaN,101.068377,535.802135,507.110855,763.028453,NaN,1491.747023,NaN,2614.311100,3889.909078,3405.176838,2294.976272,2172.353993
Ecuador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4067.123375,3317.627487,3085.430928,3098.059788,3155.030683,2505.505960,2913.652629
El Salvador,NaN,NaN,119.943505,26.873322,407.296165,96.136223,177.722356,516.782825,1021.186176,1615.384753,2179.459389,10911.689757,8175.330242,6934.887423,4896.970526,2754.741879
Grenada,14.561014,5.811870,5.803070,11.523181,14.472126,5.726685,5.786373,28.731832,8.565664,14.166308,8.523438,68.791527,42.015235,72.379188,97.109459,91.467167
Guatemala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9318.000000,8602.000000,8320.000000,10135.589702,18655.342974,13588.394913,13645.045639,6350.849323
Guyana,NaN,NaN,NaN,NaN,NaN,NaN,63.305686,43.011717,61.954094,NaN,142.448809,612.983802,426.880029,496.295723,576.083412,704.022583
Honduras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492.152282,13016.969043,13821.134805,13662.695707,17286.931701,7955.384974,11401.847840,8388.795859,7345.469203
Jamaica,NaN,533.338085,933.290362,851.408752,1019.381905,489.668913,716.548957,910.060532,1078.837066,700.783511,985.036919,61.991569,5524.741041,3764.885305,1459.191529,1427.855821
Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20676.000000,24486.000000,33491.000000,74291.107752,36429.018046,36401.355806
Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,499.521081,480.732867,737.359589,572.135924,NaN
Panama,127.176317,127.044001,140.670306,278.952497,294.536337,194.066213,262.409572,475.888402,NaN,1044.812672,1224.001018,1431.597478,1184.163435,1245.873844,973.751733,NaN
Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.760057,83.474391,78.271067,940.698728,752.173029,686.037110,213.939887,637.269127
Peru,NaN,NaN,NaN,NaN,NaN,NaN,378.569018,336.262014,385.572469,493.255595,366.385944,3912.220014,1529.702628,3654.787381,NaN,NaN
Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.857305,685.020193,10.648745,9.605220
Saint Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.000000,106.000000,91.000000,64.000000,62.000000
Saint Lucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,295.168574,221.709849,263.420080,294.010377
Saint Vincent and the Grenadines,5.644846,5.683680,20.026255,17.072503,2.878287,NaN,NaN,11.309528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.175357,152.092586,137.042052,118.988503,223.860105
Trinidad and Tobago,NaN,266.681921,313.887036,416.333583,296.210382,214.189099,189.915015,243.759030,288.411879,250.262339,223.715942,NaN,NaN,NaN,NaN,NaN
Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,72.067939,115.479244,139.811628,220.475813,641.240041,611.484119,640.913810,1358.853343,890.813608,741.358359

## Ideas para siguientes pasos:
Vemos que los datos de Latinoamérica no están tan completos, pero hay información que sí podemos obtener. Quedarnos con el total de la categoría de homicidios ayudará a no tener tantos valores nulos (aunque siguen habiendo muchos).

Ideas:
- Ver relación entre los distintos años (Coeficiente de Pearson)
- Clusterización de países (¿serán países vecinos? ¿son países con algún tipo de relación? (comercio, política, cultura, etc)) -sarygmz666
- Análisis de series temporales para la predicción de los siguientes años? (usar la idea B de base)
- Idea anterior, pero predecir 2020-2021 y ver si la pademia afectó a los índices de homicidio -wertah
- Comparativos por año (grafico de violin por año con información respecto al top x y lowest x) -joselio

Ideas locas (con datasets adicionales):
- Incluir un grafo de conectividad geográfica de países y ver si esto ayuda a afinar los modelos.